import Link from 'next/link'
import { ShieldCheck } from 'lucide-react'

const supportEmail = 'support@campuslink.name.ng'

export const metadata = {
  title: 'Privacy Policy | Kampivo',
  description: 'How Kampivo collects, uses, protects and retains personal data.',
}

export default function PrivacyPage() {
  return (
    <main className="legal-page">
      <nav className="legal-nav"><div className="legal-nav-inner"><Link className="legal-brand" href="/">Kampiv<strong>o</strong></Link><div className="legal-nav-links"><Link href="/terms">Terms</Link><Link href="/compliance">Compliance</Link><Link href="/register">Create account</Link></div></div></nav>
      <header className="legal-hero">
        <span className="legal-kicker"><ShieldCheck size={14}/> Privacy</span>
        <h1>Privacy Policy</h1>
        <p>This policy explains how Kampivo handles personal data for students, vendors, administrators and visitors. It is written for the current private-beta and launch-stage service in Nigeria.</p>
        <div className="legal-meta"><span>Effective: 7 October 2026</span><span>Nigeria Data Protection Act 2023</span><span>18+ launch policy</span></div>
      </header>
      <div className="legal-layout">
        <aside className="legal-toc"><strong>On this page</strong><a href="#who">Who we are</a><a href="#data">Data we collect</a><a href="#purposes">Why we use it</a><a href="#verification">Verification evidence</a><a href="#sharing">Processors & transfers</a><a href="#retention">Retention</a><a href="#rights">Your rights</a><a href="#deletion">Deletion & requests</a><a href="#security">Security</a><a href="#breach">Data breaches</a><a href="#children">Age policy</a><a href="#contact">Contact</a></aside>
        <article className="legal-content">
          <section className="legal-section" id="who"><h2>1. Who is responsible for your data?</h2><p>Kampivo is currently in private beta and is operated by the Kampivo project team in Nigeria. The registered operating-entity details will be added to this policy when incorporation is completed. For privacy questions and requests, contact <a href={`mailto:${supportEmail}`}>{supportEmail}</a>.</p><div className="legal-note">Kampivo does not claim NDPC registration, CAC incorporation, a Nigeria Startup Label or school endorsement until the relevant registration, label or partnership has actually been obtained.</div></section>

          <section className="legal-section" id="data"><h2>2. Personal data we collect</h2><p>The data depends on how you use Kampivo.</p><h3>Account and profile data</h3><ul><li>Name, email address, phone number, account type and authentication information.</li><li>Institution, course/level and other campus-profile information supplied by a student.</li><li>Business name, description, contact details, service areas, availability and listing information supplied by a vendor.</li></ul><h3>Verification and trust data</h3><ul><li>Student or vendor verification evidence, which may include school ID, matriculation or portal evidence, government/business documents or other evidence requested for a verification decision.</li><li>Verification status, review notes, campus-approval status and audit records.</li></ul><h3>Marketplace and safety data</h3><ul><li>Saves, reviews, ratings, contact events, reports, complaints and moderation records.</li><li>Products, services, portfolio media and pricing information.</li></ul><h3>Technical and billing data</h3><ul><li>Security/session information, device/browser information and operational logs used to protect the service.</li><li>Vendor subscription/payment references and status. Kampivo does not store full card details; payment processing is handled by the payment provider.</li></ul></section>

          <section className="legal-section" id="purposes"><h2>3. Why we process personal data</h2><p>We process data only where there is a lawful basis and for purposes connected to the service. Depending on the activity, those bases may include performance of our agreement with you, consent, legitimate interests such as platform security and fraud prevention, or compliance with legal obligations.</p><ul><li>To create and secure accounts and route users to the correct Student, Vendor or Admin experience.</li><li>To verify campus membership or vendor identity and determine campus eligibility.</li><li>To operate campus discovery, search, reviews, saves and contact features.</li><li>To investigate reports, prevent abuse and keep an audit trail of safety decisions.</li><li>To administer Vendor plans, billing and entitlements.</li><li>To send account, verification, security and service communications.</li><li>To improve reliability, diagnose errors and protect the service from misuse.</li></ul></section>

          <section className="legal-section" id="verification"><h2>4. Verification documents</h2><p>Verification evidence is used only for identity, campus eligibility, fraud prevention, safety, appeals and related legal/compliance purposes. Verification documents are kept in a private storage area and are not displayed publicly. Access is restricted to the account owner and authorised administrators with a legitimate verification or safety role.</p><p>Paying for a Kampivo plan does not buy verification, campus approval or a trust badge.</p></section>

          <section className="legal-section" id="sharing"><h2>5. Service providers, processors and international transfers</h2><p>Kampivo uses specialised service providers to run the platform. These may include cloud hosting, database/authentication, transactional email and payment providers. We disclose only what is reasonably necessary for the relevant service.</p><div className="legal-table-wrap"><table className="legal-table"><thead><tr><th>Provider category</th><th>Purpose</th><th>Typical data</th></tr></thead><tbody><tr><td>Supabase</td><td>Database, authentication and private file storage</td><td>Accounts, profiles, verification and marketplace records</td></tr><tr><td>Vercel</td><td>Web hosting, application delivery and runtime</td><td>Web requests and application traffic</td></tr><tr><td>Resend / email infrastructure</td><td>Transactional and administrative email delivery</td><td>Email address, recipient name and message content</td></tr><tr><td>Paystack</td><td>Vendor subscription payment processing</td><td>Billing email, payment/subscription references and payment status</td></tr></tbody></table></div><p>Some providers may process data outside Nigeria. Where a cross-border transfer occurs, Kampivo will use the safeguards required by applicable Nigerian data-protection law and will review the relevant provider arrangements.</p></section>

          <section className="legal-section" id="retention"><h2>6. How long we keep data</h2><p>We keep personal data only for as long as it is reasonably needed for the purpose for which it was collected, for account administration, safety, dispute handling, fraud prevention or legal obligations. Our operational retention schedule is reviewed as the service grows.</p><ul><li><strong>Account/profile data:</strong> while the account is active and for a limited period after closure where needed for recovery, disputes, fraud prevention or legal obligations.</li><li><strong>Verification evidence:</strong> only while reasonably needed for verification, appeals, fraud/safety review or a legal hold; evidence is scheduled for deletion when those purposes expire while the verification decision and minimal audit record may be retained.</li><li><strong>Reports and safety records:</strong> for the period needed to investigate, resolve and defend safety decisions.</li><li><strong>Billing/accounting records:</strong> for the period required by applicable tax, accounting and legal obligations.</li><li><strong>Operational/security logs:</strong> for a limited security and troubleshooting period unless a specific incident requires longer preservation.</li></ul></section>

          <section className="legal-section" id="rights"><h2>7. Your data-protection rights</h2><p>Subject to the Nigeria Data Protection Act and applicable limitations, you may have rights to be informed, access your data, request correction, object to or restrict certain processing, request portability, request erasure, withdraw consent where consent is the basis, request human intervention in qualifying automated decisions, and complain to the Nigeria Data Protection Commission.</p><p>We may ask for information reasonably necessary to confirm your identity before acting on a request, especially where disclosure or deletion could affect another person.</p></section>

          <section className="legal-section" id="deletion"><h2>8. Account deletion and data-subject requests</h2><p>To request access, correction, deletion, restriction, portability, objection or account closure, email <a href={`mailto:${supportEmail}?subject=Kampivo%20Privacy%20Request`}>{supportEmail}</a> with the subject <strong>Kampivo Privacy Request</strong>. Tell us the email address on your account and the request you want us to process. Do not email identity documents unless we specifically ask for verification through an appropriate channel.</p><p>We aim to acknowledge requests promptly and respond within the period required by applicable law. Complex requests may require additional verification or time permitted by law. Account deletion does not require us to erase information that must lawfully be retained for unresolved disputes, fraud prevention, safety, tax/accounting or other legal obligations.</p><div className="legal-contact"><a href={`mailto:${supportEmail}?subject=Kampivo%20Privacy%20Request`}>Make a privacy request</a><a className="secondary" href="https://ndpc.gov.ng/" target="_blank" rel="noreferrer">Nigeria Data Protection Commission</a></div></section>

          <section className="legal-section" id="security"><h2>9. Security</h2><p>Kampivo uses technical and organisational controls intended to protect personal data, including access controls, role-scoped administration, private verification-document storage, authentication controls, row-level data access rules and security logging. No internet service can promise absolute security, so we continuously review controls as the platform changes.</p></section>

          <section className="legal-section" id="breach"><h2>10. Personal-data incidents</h2><p>Kampivo maintains a breach-response process to identify, contain, assess, document and remediate suspected personal-data incidents. Where an incident is likely to create the level of risk requiring regulatory notification, we will notify the Nigeria Data Protection Commission within the applicable statutory timeframe and communicate with affected people where required.</p></section>

          <section className="legal-section" id="children"><h2>11. Age policy</h2><p>Kampivo's current launch is for people aged <strong>18 years and above</strong>. We do not intentionally onboard users we know to be under 18 during this launch phase. If we later support minors, we will introduce the additional age-verification, consent and safeguarding process required by law before doing so.</p></section>

          <section className="legal-section" id="contact"><h2>12. Contact and policy updates</h2><p>Privacy and data-subject requests: <a href={`mailto:${supportEmail}`}>{supportEmail}</a>. We may update this policy as Kampivo's company registration, domain, service providers, features or legal obligations change. Material changes will be communicated through the service or another appropriate channel.</p></section>
        </article>
      </div>
      <footer className="legal-footer"><div className="legal-footer-inner"><span>© 2026 Kampivo. Your campus. Trusted.</span><div className="legal-footer-links"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/compliance">Compliance</Link></div></div></footer>
    </main>
  )
}
