ALTER TABLE vendors 
ADD COLUMN id_number VARCHAR(100) NULL DEFAULT NULL;

ALTER TABLE vendors 
ADD COLUMN id_document VARCHAR(255) NULL DEFAULT NULL AFTER logo;

DELETE FROM vendors WHERE phone = '08137268006';