import Link from 'next/link'
import { Scale } from 'lucide-react'

const supportEmail = 'support@campuslink.name.ng'

export const metadata = {
  title: 'Terms of Use | Kampivo',
  description: 'Terms governing use of Kampivo by students, vendors and administrators.',
}

export default function TermsPage() {
  return (
    <main className="legal-page">
      <nav className="legal-nav"><div className="legal-nav-inner"><Link className="legal-brand" href="/">Kampiv<strong>o</strong></Link><div className="legal-nav-links"><Link href="/privacy">Privacy</Link><Link href="/compliance">Compliance</Link><Link href="/register">Create account</Link></div></div></nav>
      <header className="legal-hero"><span className="legal-kicker"><Scale size={14}/> Legal</span><h1>Terms of Use</h1><p>These terms set the rules for using Kampivo as a student, vendor, administrator or visitor. Please read them before creating an account.</p><div className="legal-meta"><span>Effective: 7 October 2026</span><span>Governed by Nigerian law</span><span>18+ service</span></div></header>
      <div className="legal-layout">
        <aside className="legal-toc"><strong>On this page</strong><a href="#acceptance">Acceptance</a><a href="#service">What Kampivo does</a><a href="#accounts">Accounts</a><a href="#verification">Verification</a><a href="#transactions">Student–Vendor dealings</a><a href="#vendors">Vendor obligations</a><a href="#reviews">Reviews & safety</a><a href="#subscriptions">Vendor Pro</a><a href="#prohibited">Prohibited conduct</a><a href="#suspension">Suspension</a><a href="#liability">Disclaimers</a><a href="#complaints">Complaints</a></aside>
        <article className="legal-content">
          <section className="legal-section" id="acceptance"><h2>1. Acceptance and eligibility</h2><p>By creating an account, using Kampivo or submitting information to the service, you agree to these Terms and acknowledge the Privacy Policy. You must be at least 18 years old for the current launch. If you do not agree, do not create or continue using an account.</p><p>During private beta, Kampivo is operated by the Kampivo project team in Nigeria. Registered-entity details will be added after incorporation.</p></section>

          <section className="legal-section" id="service"><h2>2. What Kampivo is</h2><p>Kampivo is a campus-focused discovery and trust platform. It helps students discover approved vendors, products and services; lets vendors build campus-facing profiles; and provides review, reporting, verification, moderation and business tools.</p><p>Kampivo is <strong>not the seller or provider</strong> of a vendor's goods or services and does not currently process Student-to-Vendor marketplace payments. Student and Vendor transactions are agreed and completed directly between those parties.</p></section>

          <section className="legal-section" id="accounts"><h2>3. Accounts and security</h2><ul><li>Provide accurate information and keep it reasonably current.</li><li>Use your own account and protect your login credentials and one-time codes.</li><li>Do not share Admin access or attempt to enter a role, campus or account you are not authorised to use.</li><li>Notify Kampivo promptly if you believe your account has been compromised.</li><li>Kampivo may require email, identity, school or business verification before enabling particular features.</li></ul></section>

          <section className="legal-section" id="verification"><h2>4. Verification, approval and trust signals</h2><p>Verification means Kampivo has reviewed the evidence required for a particular trust decision at that time. It is not a guarantee of future conduct, product quality, financial capacity, professional licensing or safety. Campus approval is campus-specific; approval to serve one institution does not automatically approve a Vendor for another institution.</p><p>Verification and campus approval are independent of payment. A Free or Pro plan cannot purchase a verification badge or override a safety decision.</p></section>

          <section className="legal-section" id="transactions"><h2>5. Dealings between Students and Vendors</h2><p>Students and Vendors are responsible for their own communications, quotations, product/service descriptions, fulfilment, payments, receipts, warranties, refunds and disputes unless Kampivo expressly states otherwise for a particular feature.</p><p>Use reasonable care before paying a Vendor. Verify the service, price, timing and identity of the person you are dealing with. Kampivo may provide reporting and moderation tools, but it cannot guarantee the outcome of an offline or third-party transaction.</p></section>

          <section className="legal-section" id="vendors"><h2>6. Vendor responsibilities</h2><ul><li>Only advertise products and services you can lawfully provide.</li><li>Keep prices, descriptions, availability and contact information accurate and not misleading.</li><li>Do not impersonate another person, business, school or authority.</li><li>Provide genuine verification evidence and promptly disclose material changes affecting eligibility.</li><li>Respect consumer rights, honour lawful commitments and respond to legitimate complaints.</li><li>Do not state or imply that a school, regulator or Kampivo guarantees your business unless that specific endorsement is true and authorised.</li></ul></section>

          <section className="legal-section" id="reviews"><h2>7. Reviews, reports and moderation</h2><p>Reviews should reflect genuine experiences and may be subject to eligibility, contact evidence, anti-spam checks and moderation. Kampivo may remove, restrict or investigate content that appears fraudulent, abusive, unsafe, defamatory, unlawful or inconsistent with these Terms.</p><p>Submitting a report does not guarantee a particular decision. Kampivo may preserve evidence, seek further information, restrict marketplace visibility or refer serious issues to appropriate authorities where legally required or reasonably necessary.</p></section>

          <section className="legal-section" id="subscriptions"><h2>8. Vendor Free and Pro plans</h2><p>Students browse and contact vendors without a Kampivo subscription charge. Vendors may use a Free plan or purchase optional Pro business tools. Current prices, billing period and included features are displayed before checkout.</p><p>Vendor subscription payments are processed by the payment provider. Kampivo does not store full card details. Renewal, cancellation and subscription-management options are presented through the billing experience. Except where law requires otherwise or Kampivo expressly states otherwise, fees already charged for a billing period are not automatically refundable merely because a Vendor stops using the service during that period.</p><p>Paid features never determine verification, campus approval or safety status.</p></section>

          <section className="legal-section" id="prohibited"><h2>9. Prohibited conduct and content</h2><ul><li>Fraud, scams, deceptive pricing, fake reviews or falsified verification documents.</li><li>Harassment, threats, hate, sexual exploitation, stalking or unsafe conduct.</li><li>Illegal goods or services, stolen goods, counterfeit items or content that violates third-party rights.</li><li>Attempts to bypass access controls, scrape protected information, exploit vulnerabilities or interfere with Kampivo's systems.</li><li>Publishing another person's sensitive or private information without a lawful reason.</li><li>Using Kampivo to facilitate conduct prohibited by Nigerian law or applicable campus rules.</li></ul></section>

          <section className="legal-section" id="suspension"><h2>10. Restriction, suspension and termination</h2><p>Kampivo may limit, suspend or terminate access where reasonably necessary for safety, fraud prevention, legal compliance, repeated Terms violations, false verification, security incidents or platform integrity. Where appropriate, we may provide notice or an opportunity to explain or appeal a decision.</p><p>You may request account closure through the privacy/contact process. Certain records may be retained where necessary for unresolved disputes, safety, fraud prevention, accounting or legal obligations.</p></section>

          <section className="legal-section" id="intellectual"><h2>11. Content and intellectual property</h2><p>You keep ownership of content you lawfully submit. You give Kampivo a non-exclusive permission to host, reproduce, resize and display that content as needed to operate and promote the relevant listing or profile within the service. You represent that you have the rights required to upload the content.</p><p>Kampivo's software, brand, design and original platform content remain protected by applicable intellectual-property law.</p></section>

          <section className="legal-section" id="liability"><h2>12. Service availability and liability</h2><p>Kampivo is provided on an evolving basis. We aim for reliable service but do not promise uninterrupted availability or that every Vendor, review or user statement will always be error-free. Nothing in these Terms excludes a right or liability that cannot lawfully be excluded under Nigerian law.</p><p>To the extent permitted by law, Kampivo is not responsible for losses caused solely by a direct transaction or private arrangement between a Student and Vendor where Kampivo is not a party to that transaction. This does not limit Kampivo's responsibility for its own legal obligations, including applicable data-protection and consumer-protection duties.</p></section>

          <section className="legal-section" id="complaints"><h2>13. Complaints and dispute resolution</h2><p>For account, billing, safety or consumer complaints, email <a href={`mailto:${supportEmail}?subject=Kampivo%20Complaint`}>{supportEmail}</a>. Provide enough information for us to identify the account or issue without sending unnecessary sensitive documents.</p><p>We aim to acknowledge and investigate complaints fairly. Nothing in these Terms prevents you from using a statutory complaint mechanism available under Nigerian law, including the Nigeria Data Protection Commission for data-protection matters or the Federal Competition and Consumer Protection Commission for qualifying consumer matters.</p></section>

          <section className="legal-section" id="changes"><h2>14. Changes, governing law and contact</h2><p>We may update these Terms as Kampivo develops, including when the operating entity, domain or commercial features change. Material changes will be communicated appropriately. These Terms are governed by the laws of the Federal Republic of Nigeria.</p><div className="legal-contact"><a href={`mailto:${supportEmail}`}>Contact Kampivo</a><Link className="secondary" href="/privacy">Read Privacy Policy</Link></div></section>
        </article>
      </div>
      <footer className="legal-footer"><div className="legal-footer-inner"><span>© 2026 Kampivo. Your campus. Trusted.</span><div className="legal-footer-links"><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/compliance">Compliance</Link></div></div></footer>
    </main>
  )
}
