import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { Bookmark, Flag, MapPin, MessageCircle, Package, ShieldCheck, Star } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import { ThemeToggle } from '@/components/theme-toggle'
import { reportVendor, submitReview, toggleSavedVendor } from '../../actions'

export default async function VendorProfilePage({ params, searchParams }: { params: Promise<{ slug: string }>; searchParams: Promise<{ error?: string; review?: string; reported?: string }> }) {
  const { slug } = await params, notices = await searchParams, supabase = await createClient()
  const { data: claimsData } = await supabase.auth.getClaims(); const userId=claimsData?.claims?.sub; if(!userId) redirect('/login')
  const {data:profile}=await supabase.from('profiles').select('account_type,institution_id,student_verification_status,onboarding_completed_at').eq('id',userId).single()
  if(!profile||profile.account_type!=='student') redirect('/dashboard'); if(!profile.onboarding_completed_at||!profile.institution_id) redirect('/onboarding/student')
  const {data:vendor}=await supabase.from('vendor_profiles').select('id,business_name,slug,description,location_text,logo_url,cover_url,average_rating,review_count,verification_status,marketplace_status,suspended_until').eq('slug',slug).eq('verification_status','approved').maybeSingle(); if(!vendor) notFound()
  const safetyAllowed=vendor.marketplace_status==='active'||(vendor.marketplace_status==='suspended'&&vendor.suspended_until&&new Date(vendor.suspended_until)<=new Date()); if(!safetyAllowed) notFound()
  const {data:campusApproval}=await supabase.from('vendor_institutions').select('vendor_id').eq('vendor_id',vendor.id).eq('institution_id',profile.institution_id).eq('status','approved').maybeSingle(); if(!campusApproval) notFound()
  const [{data:products},{data:services},{data:reviews},{data:saved},{data:institution},{data:portfolio}]=await Promise.all([
    supabase.from('vendor_products').select('id,name,description,price_ngn,pricing_type,cover_image_url').eq('vendor_id',vendor.id).eq('is_active',true).order('sort_order').order('created_at',{ascending:false}),
    supabase.from('vendor_services').select('id,name,description,price_from').eq('vendor_id',vendor.id).eq('is_active',true).order('name'),
    supabase.from('reviews').select('id,rating,comment,created_at').eq('vendor_id',vendor.id).eq('status','published').order('created_at',{ascending:false}).limit(20),
    supabase.from('saved_vendors').select('vendor_id').eq('student_id',userId).eq('vendor_id',vendor.id).maybeSingle(),
    supabase.from('institutions').select('name').eq('id',profile.institution_id).maybeSingle(),
    supabase.from('vendor_portfolio_items').select('id,title,description,image_url,sort_order').eq('vendor_id',vendor.id).eq('is_active',true).order('sort_order').order('created_at',{ascending:false}),
  ])
  const initial=vendor.business_name?.slice(0,1)?.toUpperCase()||'V', returnTo=`/student/vendors/${vendor.slug}`
  return <main className="v3-student-page"><header className="v3-appbar"><div className="v3-appbar-inner"><Link href="/student" className="v3-brand">Campus<span>Link</span></Link><div style={{display:'flex',alignItems:'center',gap:8}}><nav className="v3-nav"><Link href="/student">Home</Link><Link href="/student/discover">Discover</Link><Link href="/student/saved">Saved</Link></nav><ThemeToggle compact/></div></div></header><section className="v3-shell">{notices.error?<div className="notice error">{notices.error}</div>:null}{notices.review==='saved'?<div className="notice success">Your review has been saved.</div>:null}{notices.reported==='1'?<div className="notice success">Your report has been submitted for review.</div>:null}<section className="v3-surface" style={{padding:0,overflow:'hidden'}}><div style={{height:250,background:'var(--v3-soft-blue)',overflow:'hidden'}}>{vendor.cover_url?<img src={vendor.cover_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:null}</div><div style={{padding:'0 clamp(20px,4vw,44px) 36px'}}><div style={{width:82,height:82,borderRadius:22,marginTop:-42,border:'5px solid var(--v3-surface)',background:'var(--v3-navy)',color:'#fff',overflow:'hidden',display:'grid',placeItems:'center',fontWeight:900,fontSize:28,position:'relative'}}>{vendor.logo_url?<img src={vendor.logo_url} alt="" style={{width:'100%',height:'100%',objectFit:'cover'}}/>:initial}</div><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start',flexWrap:'wrap',marginTop:16}}><div style={{maxWidth:720}}><div className="v3-trust-line" style={{borderTop:0,paddingTop:0}}><ShieldCheck size={16}/> Verified for {institution?.name||'your campus'}</div><h1 style={{fontSize:'clamp(34px,5vw,58px)',letterSpacing:'-.05em',margin:'10px 0'}}>{vendor.business_name}</h1><div style={{display:'flex',gap:14,flexWrap:'wrap',color:'var(--v3-muted)',fontSize:14}}><span><Star size={14} fill="currentColor"/> {Number(vendor.average_rating||0).toFixed(1)} ({vendor.review_count||0})</span>{vendor.location_text?<span><MapPin size={14}/> {vendor.location_text}</span>:null}</div><p style={{color:'var(--v3-muted)',lineHeight:1.7}}>{vendor.description||'Verified Campus Link vendor.'}</p></div><div style={{display:'grid',gap:9,minWidth:210}}><Link className="btn btn-primary" href={`/student/vendors/${vendor.slug}/contact`}><MessageCircle size={17}/> WhatsApp vendor</Link><form action={toggleSavedVendor}><input type="hidden" name="vendor_id" value={vendor.id}/><input type="hidden" name="return_to" value={returnTo}/><button className="btn btn-ghost" style={{width:'100%'}}><Bookmark size={17} fill={saved?'currentColor':'none'}/> {saved?'Saved':'Save vendor'}</button></form></div></div></div></section>
  {(products||[]).length?<section className="v3-section"><div className="v3-section-head"><div><small>Products</small><h2>What {vendor.business_name} sells</h2></div></div><div className="v3-product-rail">{(products||[]).map(p=><Link href={`/student/products/${p.id}`} className="v3-product-card" key={p.id}><div className="v3-product-image">{p.cover_image_url?<img src={p.cover_image_url} alt={p.name}/>:<Package size={32}/>}</div><div className="v3-product-copy"><strong>{p.name}</strong><p>{p.description||'Open this item to ask the vendor about it.'}</p><div className="v3-product-meta"><span>{p.pricing_type==='contact'?'Ask for price':`${p.pricing_type==='from'?'From ':''}₦${Number(p.price_ngn||0).toLocaleString()}`}</span><small>View</small></div></div></Link>)}</div></section>:null}
  <section className="v3-section"><div className="v3-section-head"><div><small>Services</small><h2>What this vendor does</h2></div></div><div className="v3-surface">{(services||[]).length?(services||[]).map(s=><div className="v3-action-row" key={s.id}><span><ShieldCheck size={17}/></span><div><strong>{s.name}</strong><small>{s.description||'Contact vendor for details.'}</small></div><strong>{s.price_from?`From ₦${Number(s.price_from).toLocaleString()}`:'Ask vendor'}</strong></div>):<p>No detailed services added yet.</p>}</div></section>
  {(portfolio||[]).length?<section className="v3-section"><div className="v3-section-head"><div><small>Portfolio</small><h2>Proof of work</h2></div></div><div style={{columns:'3 240px',columnGap:14}}>{(portfolio||[]).map(item=><figure key={item.id} className="v3-surface" style={{breakInside:'avoid',padding:0,overflow:'hidden',margin:'0 0 14px'}}><img src={item.image_url} alt={item.title} style={{width:'100%',height:'auto',display:'block'}}/><figcaption style={{padding:14}}><strong>{item.title}</strong>{item.description?<p style={{color:'var(--v3-muted)',fontSize:13}}>{item.description}</p>:null}</figcaption></figure>)}</div></section>:null}
  <section className="v3-split v3-section"><div className="v3-surface"><div className="v3-section-head"><div><small>Community feedback</small><h2>Student reviews</h2></div></div>{(reviews||[]).map(r=><article className="v3-action-row" key={r.id}><span><Star size={17}/></span><div><strong>Verified student · {r.rating}/5</strong><small>{r.comment||'Rating only'}</small></div></article>)}{!(reviews||[]).length?<p>No published reviews yet.</p>:null}{profile.student_verification_status==='verified'?<form className="review-form" action={submitReview} style={{marginTop:18}}><input type="hidden" name="vendor_id" value={vendor.id}/><input type="hidden" name="slug" value={vendor.slug}/><strong>Share your experience</strong><select name="rating" required defaultValue=""><option value="" disabled>Choose rating</option><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select><textarea name="comment" maxLength={1000} placeholder="Keep your review factual and helpful."/><button className="btn btn-primary">Submit review</button></form>:null}</div><aside className="v3-surface"><div className="v3-section-head"><div><small>Safety</small><h2>Report a concern</h2></div></div><p style={{color:'var(--v3-muted)',lineHeight:1.6}}>Reports are private. Five distinct unresolved reports in the safety window automatically remove a vendor from student discovery while Campus Link reviews the case.</p><form className="report-form" action={reportVendor}><input type="hidden" name="vendor_id" value={vendor.id}/><input type="hidden" name="slug" value={vendor.slug}/><input name="title" minLength={4} maxLength={120} required placeholder="What happened?"/><textarea name="description" minLength={10} maxLength={1500} required placeholder="Give enough factual detail for review."/><button className="danger-cta"><Flag size={17}/> Submit report</button></form></aside></section></section></main>
}
